version: '3.3'

services:
  mariadb:
    image: mariadb:bionic
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/.data/mysql:/var/lib/mysql:cached
      - ./docker/optimize.cnf:/etc/mysql/conf.d/optimize.cnf:cached

networks:
  default:
    driver: "bridge"

